[tox]
minversion = 4.6
envlist = py311, py312
isolated_build = true


[testenv]
description = Run automated tests with pytest
deps =
    -r {toxinidir}/requirements.txt
setenv =
    PYTHONPATH = {toxinidir}/src
passenv =
    HOME
    SETUPTOOLS_*
commands =
    pytest -q
    # pytest {posargs:-q}


[testenv:{build,clean}]
description =
    build: Build the package in isolation according to PEP517
    clean: Remove build artifacts
skip_install = true
changedir = {toxinidir}
deps =
    build: build[virtualenv]
commands =
    clean: python -c 'import shutil; [shutil.rmtree(p, True) for p in ("build", "dist", "docs/_build")]'
    clean: python -c 'import pathlib, shutil; [shutil.rmtree(p, True) for p in pathlib.Path("src").glob("*.egg-info")]'
    build: python -m build {posargs}


[testenv:{docs,doctests,linkcheck}]
description =
    docs: Build Sphinx HTML documentation
    doctests: Run Sphinx doctests
    linkcheck: Check documentation links
skip_install = true
passenv = SETUPTOOLS_*
setenv =
    DOCSDIR = {toxinidir}/docs
    BUILDDIR = {toxinidir}/docs/_build
    docs: BUILD = html
    doctests: BUILD = doctest
    linkcheck: BUILD = linkcheck
deps =
    -r {toxinidir}/docs/requirements.txt
commands =
    sphinx-build --color -b {env:BUILD} -d "{env:BUILDDIR}/doctrees" "{env:DOCSDIR}" "{env:BUILDDIR}/{env:BUILD}" {posargs}


[testenv:publish]
description = Upload built distributions via Twine
skip_install = true
deps = twine
changedir = {toxinidir}
passenv =
    TWINE_USERNAME
    TWINE_PASSWORD
    TWINE_REPOSITORY
    TWINE_REPOSITORY_URL
commands =
    python -m twine check dist/*
    python -m twine upload {posargs:--repository {env:TWINE_REPOSITORY:testpypi}} dist/*


[testenv:flake8]
description = Run flake8 on the codebase
skip_install = true
deps =
    flake8
    flake8-bugbear
    flake8-docstrings>=1.3.1
    flake8-typing-imports>=1.1
    pep8-naming
commands =
    flake8 {posargs} src tests
